device_type: hi6220-hikey
job_name: Jessie LXC and Android boot.img
timeouts:
  job:
    minutes: 60
  action:
    minutes: 15
  connection:
    minutes: 2
priority: medium
visibility: public

metadata:
  source: https://git.linaro.org/lava/lava-lab.git
  path: shared/health-checks/hi6220-hikey.yaml

protocols:
  lava-lxc:
    name: lxc-hikey-test
    template: debian
    distribution: debian
    release: jessie
    arch: amd64
    mirror: http://mirror.bytemark.co.uk/debian
    verbose: true

actions:
- deploy:
    namespace: tlxc
    timeout:
      minutes: 5
    to: lxc
    packages:
    - android-tools-adb
    - android-tools-fastboot
    os: debian

- boot:
    namespace: tlxc
    prompts:
    - 'root@(.*):'
    - 'hikey: '
    timeout:
      minutes: 5
    method: lxc

- deploy:
    timeout:
      minutes: 15
    to: fastboot
    namespace: droid
    images:
      ptable:
        url: https://builds.96boards.org/releases/reference-platform/aosp/hikey/16.03/bootloader/ptable-aosp-8g.img
        reboot: hard-reset
      boot:
        url: http://images.validation.linaro.org/builds.96boards.org/snapshots/hikey/linaro/aosp-master/357/boot.img.xz
        compression: xz
        reboot: hard-reset
      cache:
        url: http://images.validation.linaro.org/builds.96boards.org/snapshots/hikey/linaro/aosp-master/357/cache.img.xz
        compression: xz
      userdata:
        url: http://images.validation.linaro.org/builds.96boards.org/snapshots/hikey/linaro/aosp-master/357/userdata.img.xz
        compression: xz
      system:
        url: http://images.validation.linaro.org/builds.96boards.org/snapshots/hikey/linaro/aosp-master/357/system.img.xz
        compression: xz
    os: debian
    protocols:
        lava-lxc:
        - action: fastboot-deploy
          request: pre-power-command
          timeout:
              minutes: 2

- boot:
    namespace: droid
    prompts:
    - 'root@(.*):/#'
    - 'hikey:/'
    timeout:
      minutes: 15
    method: fastboot

- test:
    namespace: tlxc
    timeout:
      minutes: 5
    definitions:
    - repository:
        metadata:
          name: get-adb-serial-number
          format: "Lava-Test-Shell Test Definition 1.0"
          description: "Gets the adb serial number"
          maintainer:
            - senthil.kumaran@linaro.org
          os:
            - debian
          devices:
            - lxc
          scope:
            - functional
        run:
          steps:
            - lava-lxc-device-add
            - adb start-server
            - adb devices
      from: inline
      path: inline/get-adb-serial.yaml
      name: get-adb-serial

    - repository: https://git.linaro.org/lava-team/lava-functional-tests.git
      from: git
      path: lava-test-shell/android/get-adb-serial-hikey.yaml
      name: get-hikey-serial

    - from: inline
      name: add-device-to-lxc
      path: inline/hikey-target.yaml
      repository:
        metadata:
          description: hikey target tests
          format: Lava-Test Test Definition 1.0
          name: hikey-target
        run:
          steps:
          - ls -lR /dev/bus/usb
          - lava-lxc-device-add
    - from: inline
      name: check-device-in-lxc
      path: inline/hikey-target.yaml
      repository:
        metadata:
          description: hikey target tests
          format: Lava-Test Test Definition 1.0
          name: hikey-target-check
        run:
          steps:
          - ls -lR /dev/bus/usb
    - repository: https://git.linaro.org/lava-team/refactoring.git/
      from: git
      path: android/lava-android-basic-lxc.yaml
      name: v2-make-adb-connection
