- job:
    name: trigger-openembedded-lkft-linux-mainline
    project-type: freestyle
    defaults: global
    logrotate:
        daysToKeep: 30
        numToKeep: 30
    properties:
        - authorization:
            anonymous:
                - job-read
                - job-extended-read
    parameters:
        - string:
            name: KERNEL_BRANCH
            default: 'master'
    disabled: false
    node: master
    display-name: 'Trigger for LKFT - Linux Mainline'
    scm:
        - git:
            url: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git
            refspec: +refs/heads/${KERNEL_BRANCH}:refs/remotes/origin/${KERNEL_BRANCH}
            name: origin
            branches:
                - origin/${KERNEL_BRANCH}
            skip-tag: true
            shallow-clone: false
            wipe-workspace: false
    triggers:
        - pollscm: 'H/5 * * * *'
    wrappers:
        - timestamps
        - build-name:
            name: '#${BUILD_NUMBER}-${GIT_REVISION,length=8}'
    builders:
        - shell: |
            #!/bin/bash -e
            echo KERNEL_DESCRIBE=$(git describe --always) > lkft_parameters
            echo SRCREV_kernel=${GIT_COMMIT} >> lkft_parameters
            echo MAKE_KERNELVERSION=$(make kernelversion) >> lkft_parameters
            cat lkft_parameters
    publishers:
        - trigger-parameterized-builds:
            - project:
                - 'openembedded-lkft-linux-mainline'
              condition: SUCCESS
              property-file: lkft_parameters
